### ISSUE TITLE
Como equipo de trabajo necesito crear el formato de casos de uso extendido 

### ISSUE THREAD

**Issue by fawong2710** [fawong2710/5BSS#63]
para evidenciar el paso a paso de los casos de uso

**Comment by jn2020** [comment]
[Casos de Uso formato extendido 5BSS -TERMINADO.docx](https://github.com/fawong2710/5BSS/files/3963235/Casos.de.Uso.formato.extendido.5BSS.-TERMINADO.docx)

**Comment by fawong2710** [comment]
ok
