### ISSUE TITLE
Como equipo de trabajo necesito crear el diagrama de casos de uso del administrador

### ISSUE THREAD

**Issue by fawong2710** [fawong2710/5BSS#68]
Para visualizar graficamente que actividades tiene bajo su control cada usuario

**Comment by jn2020** [comment]
![ISSUESADMIN](https://user-images.githubusercontent.com/54606142/70764071-54fb3980-1d24-11ea-90d6-a3e1f1cba112.jpg)

**Comment by fawong2710** [comment]
ok
