### ISSUE TITLE
Como grupo de trabajo necesito tener actualizado el informe de calidad #52

### ISSUE THREAD

**Issue by fawong2710** [fawong2710/5BSS#79]
Se requiere presentar el informe de calidad actualizado

**Comment by Andresbass16** [comment]
[CALIDAD.xlsx](https://github.com/fawong2710/BIS-Proyect/files/7696153/CALIDAD.xlsx)
[Modelo de calidad..docx](https://github.com/fawong2710/BIS-Proyect/files/7696154/Modelo.de.calidad.docx)

**Comment by Andresbass16** [comment]
envio informe actualizado
